{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "UberProject-EntityService",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberProject-EntityService-0.0.1-SNAPSHOT-plain.jar",
          "url": "UberProject-EntityService-0.0.1-SNAPSHOT-plain.jar",
          "size": 13936,
          "sha512": "e64f66da168fc5c8d39931388fc73b20ba79aa9370b58e7c3eb105b6d9496a47402ddfc3a7e98c3a0247165f36d5317d1327d938a92dc80ead1c1eebbc9dcb69",
          "sha256": "e97c694edc33c27e869d0d58a5378a555d746eeda3b00fcab6bd3aafa19af096",
          "sha1": "b6852bcce3563fa6c3169d19c0c210b696fd4c11",
          "md5": "f9f672d56988ad0d70891ace1c2f6d0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "8.4.4"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "UberProject-EntityService-0.0.1-SNAPSHOT-plain.jar",
          "url": "UberProject-EntityService-0.0.1-SNAPSHOT-plain.jar",
          "size": 13936,
          "sha512": "e64f66da168fc5c8d39931388fc73b20ba79aa9370b58e7c3eb105b6d9496a47402ddfc3a7e98c3a0247165f36d5317d1327d938a92dc80ead1c1eebbc9dcb69",
          "sha256": "e97c694edc33c27e869d0d58a5378a555d746eeda3b00fcab6bd3aafa19af096",
          "sha1": "b6852bcce3563fa6c3169d19c0c210b696fd4c11",
          "md5": "f9f672d56988ad0d70891ace1c2f6d0c"
        }
      ]
    }
  ]
}
